---
abstract: 'Determine if a string is a palindrome'
author:
  - 'Adam Lesperance <lespea@gmail.com>'
build_requires:
  Data::Dumper: 0
  English: 0
  File::Find: 0
  File::Temp: 0
  Module::Build: 0.3601
  Test::More: 0
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.102221, CPAN::Meta::Converter version 2.102160'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: String-Palindrome
requires:
  Exporter: 0
  perl: 5.006
  vars: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=String-Palindrome
  repository: git://github.com/lespea/String-Palindrome
version: 1.02
